version: 2

sources:
  - name: raw_layer
    database:  "{{ 'SNOWFLAKE_MEDALLION_PROD' if target.name == 'prod' else 'SNOWFLAKE_MEDALLION' }}"
    schema: RAW
    tables:
      - name: clientes
      - name: pedidos
